#!/usr/bin/env node
// Generates worker/src/data.js — the FULL registry, including Pro source. This
// file is bundled into the deployed Worker only; it is a build artifact
// (gitignored) and must never be published to a CDN or the npm package. The
// Worker releases Pro payloads only after a successful license check.

import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readAllEntries } from "../../scripts/lib/read-registry.mjs";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(scriptDir, "..", "src", "data.js");

function main() {
  const entries = readAllEntries();
  const banner =
    "// AUTO-GENERATED by worker/scripts/build-data.mjs. Do not edit by hand.\n" +
    "// Contains full registry source (incl. Pro) — bundled into the Worker only.\n";
  const body = `export const ENTRIES = ${JSON.stringify(entries, null, 2)};\n`;
  writeFileSync(outFile, `${banner}\n${body}`, "utf8");
  console.error(`build-data: wrote ${entries.length} full entries to worker/src/data.js`);
}

main();
